# Generated by Django 4.0.3 on 2022-04-05 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('issuing_org', models.CharField(max_length=250)),
                ('portal', models.CharField(max_length=120)),
                ('url', models.URLField(blank=True)),
            ],
        ),
    ]
