# Generated by Django 4.0.3 on 2022-04-05 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_rename_title_certificate_title_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='description',
            field=models.TextField(default='My descr', max_length=1000),
        ),
    ]
