# Generated by Django 2.2.4 on 2022-05-26 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_project_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='serial_no',
            field=models.IntegerField(default=99),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
