# Generated by Django 2.2.4 on 2022-11-13 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_auto_20220527_0253'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('serial_no',)},
        ),
    ]
